name: verific

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout Yosys
        uses: actions/checkout@v4

      - name: Runtime environment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "procs=$(nproc)" >> $GITHUB_ENV

      - name: Build Yosys
        run: |
          make config-clang
          echo "ENABLE_VERIFIC := 1" >> Makefile.conf
          echo "ENABLE_VERIFIC_EDIF := 1" >> Makefile.conf
          echo "ENABLE_VERIFIC_LIBERTY := 1" >> Makefile.conf
          echo "ENABLE_CCACHE := 1" >> Makefile.conf
          make -j${{ env.procs }}
